[tool.black]
line-length = 110
target-version = ["py311"]

[tool.ruff]
line-length = 110
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors (PEP8 style)
    "F",    # pyflakes (detects real code errors)
    "I",    # isort (import sorting)
    "B",    # bugbear (common Python bugs)
    "UP",   # pyupgrade (suggest modern syntax)
    "N",    # naming conventions
    "S",    # security issues (Bandit rules)
    "C4",   # flake8-comprehensions
    "DTZ",  # datetime timezone issues
]

ignore = [
    "E203",  # whitespace before ':'
    "E501",  # line too long
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.lint.mccabe]
max-complexity = 8

[tool.ruff.lint.pydocstyle]
convention = "google"

