[tool.black]
line-length = 110
target-version = ["py311"]

[tool.ruff]
line-length = 110
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors (PEP8 style)
    "F",    # pyflakes (detects real code errors)
    "I",    # isort (import sorting)
    "B",    # bugbear (common Python bugs)
    "UP",   # pyupgrade (suggest modern syntax)
    "N",    # naming conventions
    "S",    # security issues (Bandit rules)
    "C4",   # flake8-comprehensions
    "DTZ",  # datetime timezone issues
]

ignore = [
    "E203",  # whitespace before ':'
    "E501",  # line too long
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.lint.mccabe]
max-complexity = 8

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.11"

# --- Core strictness ---
disallow_untyped_defs = true          # every function must have type hints
disallow_incomplete_defs = true       # no partially-typed functions
check_untyped_defs = true             # also type-check functions without hints
disallow_untyped_decorators = true    # decorators must be typed
no_implicit_optional = true           # `Optional` must be explicit, not inferred

# --- Return and flow checks ---
warn_return_any = false               # disable overly strict Any return warnings
warn_no_return = true                 # function with no return path = error
warn_unreachable = true               # dead code flagged
strict_equality = true                # check `==` vs `is` properly

# --- Ignored/unused annotations ---
warn_redundant_casts = true           # useless casts flagged
warn_unused_ignores = false           # allow defensive type ignore comments
warn_unused_configs = true            # warn about unused config entries

# --- Developer visibility ---
show_error_codes = true               # show mypy error codes

# --- Keep mypy as strict as possible ---
allow_redefinition = false            # prevent accidental variable redefs
local_partial_types = false           # partial annotations not allowed

# --- Per-module overrides for external libs without stubs ---
[[tool.mypy.overrides]]
module = [
    "flask_cors.*",
    "marshmallow.*",
    "pymongo.*",
    "bson.*",
]
ignore_missing_imports = true

# Ignore certain files that are primarily infrastructure and harder to type
[[tool.mypy.overrides]]
module = [
    "app.utils.structured_logging",
    "app.middleware.*",
]
disallow_untyped_defs = false
check_untyped_defs = false
